#static_monitors = "/data/dev/autokuma/monitors"
default_settings = '''
keyword.headers: { "X-Bypass-Auth": "dRpM3EPTDgtELcLBGzhgwPuzje5F3XcPf6eH44gMUnPWvj3Wie8xCPVXbC8oSrDs" }
docker.docker_host: 1
docker.docker_container: {{container_name}}
*.notification_id_list: { "6": true }
*.max_retries: 3
'''

[kuma]
# url = "http://127.0.0.1:3001/"
url = "https://status.bigboot.dev/"
headers = [
    "X-Bypass-Auth=dRpM3EPTDgtELcLBGzhgwPuzje5F3XcPf6eH44gMUnPWvj3Wie8xCPVXbC8oSrDs",
]
# call_timeout = 60
# sync_interval = 0.0

# username = "marco"
# password = "buaHEfyFDzweRUUSv8VD2xcTosiTXMFbsoyX7o5RJsygAMsYVebKGTWyevkABe6m"

[docker]
socket_path = "./docker.sock"
# label_prefix = "kuma"
