ARG FEATURES=

FROM rust:1.81 AS builder
ARG FEATURES
WORKDIR /usr/src/autokuma
COPY . .
RUN --mount=type=cache,target=/cache,sharing=locked \
    cargo install --features "${FEATURES}" --locked --target-dir /cache --path ./kuma-cli 
 
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y \
    ca-certificates \
    libssl3 \
    && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/kuma /usr/local/bin/kuma

ENTRYPOINT ["kuma"]
CMD ["--help"]