name: Build and Publish to the Snap Store

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build snap
      uses: snapcore/action-build@v1
      id: build

    - name: Install snap
      run: |
        sudo snap install --dangerous kuma_*.snap
        snap info kuma
        kuma --help

    - name: Publish snap
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
      if: env.SNAPCRAFT_STORE_CREDENTIALS
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: latest/${{ startsWith(github.ref, 'refs/tags/') && 'candidate' || 'edge'}}
